/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecalculator;

/**
 *
 * @author edw_rd
 */
public class Calculator extends javax.swing.JDialog {

    /**
     * Creates new form Calculator
     */
    public Calculator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNumberTxtField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        substrButton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        delenieButton = new javax.swing.JButton();
        secondNumberTxtField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        firstNumberTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberTxtFieldActionPerformed(evt);
            }
        });

        addButton.setText("+");
        addButton.setToolTipText("");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        substrButton.setText("-");
        substrButton.setToolTipText("");
        substrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substrButtonActionPerformed(evt);
            }
        });

        multButton.setText("*");
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        delenieButton.setText("/");
        delenieButton.setToolTipText("");
        delenieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delenieButtonActionPerformed(evt);
            }
        });

        secondNumberTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNumberTxtFieldActionPerformed(evt);
            }
        });

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secondNumberTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(firstNumberTxtField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(substrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delenieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(firstNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(secondNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delenieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        addButton.getAccessibleContext().setAccessibleName("Add");
        substrButton.getAccessibleContext().setAccessibleName("Substr");
        multButton.getAccessibleContext().setAccessibleName("Mult");
        delenieButton.getAccessibleContext().setAccessibleName("Delenie");
        secondNumberTxtField.getAccessibleContext().setAccessibleName("FirstNumber");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNumberTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNumberTxtFieldActionPerformed
    
    
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        try{
            String firstNumber = this.firstNumberTxtField.getText();
            String secondNumber = this.secondNumberTxtField.getText();
            double firstNumbInt = Double.parseDouble(firstNumber);
            double secondNumbInt = Double.parseDouble(secondNumber);
            double sum = firstNumbInt + secondNumbInt;
            
            if(sum%2>0){
                this.resultLabel.setText(String.valueOf(sum));
            }
            else
                sum = (int)sum;
                this.resultLabel.setText(String.valueOf(sum));
        } catch (NumberFormatException ex){
            this.resultLabel.setText("Wrong input, please try again");
            
        }
       
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void secondNumberTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNumberTxtFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_secondNumberTxtFieldActionPerformed

    private void substrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substrButtonActionPerformed
        
       try{
            String firstNumber = this.firstNumberTxtField.getText();
            String secondNumber = this.secondNumberTxtField.getText(); 
            double firstNumbInt = Double.parseDouble(firstNumber);
            double secondNumbInt = Double.parseDouble(secondNumber);
            double subst = firstNumbInt - secondNumbInt;
        this.resultLabel.setText(String.valueOf(subst)); 
       } catch(NumberFormatException ex){
            this.resultLabel.setText("Wrong input, please try again");           
       }
        
    }//GEN-LAST:event_substrButtonActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
       try{
            String firstNumber = this.firstNumberTxtField.getText();
            String secondNumber = this.secondNumberTxtField.getText(); 
            double firstNumbInt = Double.parseDouble(firstNumber);
            double secondNumbInt = Double.parseDouble(secondNumber);
            double mult = firstNumbInt * secondNumbInt;
            this.resultLabel.setText(String.valueOf(mult)); 
       } catch(NumberFormatException ex){
           this.resultLabel.setText("Wrong input, please try again");
       }  
    }//GEN-LAST:event_multButtonActionPerformed

    private void delenieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delenieButtonActionPerformed
      
            String firstNumber = this.firstNumberTxtField.getText();
            String secondNumber = this.secondNumberTxtField.getText(); 
            double firstNumbInt = Double.parseDouble(firstNumber);
            double secondNumbInt = Double.parseDouble(secondNumber);
        try{
            double delenie = firstNumbInt / secondNumbInt;
            this.resultLabel.setText(String.valueOf(delenie)); 
       } catch(NumberFormatException ex){
           this.resultLabel.setText("Wrong input, please try again");
       }  catch(ArithmeticException ex){
           this.resultLabel.setText("Delenie na nol, please try again" + ex);
           secondNumbInt = 0;
       }
    }//GEN-LAST:event_delenieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator dialog = new Calculator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton delenieButton;
    private javax.swing.JTextField firstNumberTxtField;
    private javax.swing.JButton multButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField secondNumberTxtField;
    private javax.swing.JButton substrButton;
    // End of variables declaration//GEN-END:variables
}
